# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello_world_job"
  hello_world_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      
    #Install packages
    - name: Install packages
      run: npm install --save katalon-studio/katalon-agent#v1.4.0
    
    #Install Katalon Studio
    - name: Install Katalon Studio
      run: cd node_modules/katalon-cli/src; node remote-downloader.js  
    
    #Runs Katalon Studio Action
    #- name: Katalon Studio Action Step
    #  uses: ./  #Uses an action in the root directory

    # Runs the action
    #- name: Hello world action step
    #  uses: ./ #Uses an action in the root directory
    #  id: hello
    #  with: 
    #   who-to-greet: 'Mona the Octocat'

    # Uses the output from the 'hello' step
    #- name: Get the output time
    #  run: echo "The time was ${{ steps.hello.outputs.time }}"
